default:
  image: python:3.9

stages:
  - build
  - test

before_script:
  - echo "put common things here"

build:
  stage: build
  script:
    - python -V
    - python3 -V
    - pip list
    - echo "put build here"

test:
  stage: test
  script:
    - wget https://bootstrap.pypa.io/pip/3.5/get-pip.py
    - python3 get-pip.py --user
    - python3 -m pip install pytest
    - python3 -m pip install ply
    - pytest
